In [1]:
### STEP 1: IMPORT REQUIRED LIBRARIES
import pandas as pd
import numpy as np

In [2]:
###STEP 2: LOAD DATASET
df=pd.read_csv(r"C:\Users\DELL\Downloads\loan_data.csv")
df.head()

   age  income  credit_score  loan_amount  approval_status
0   59   40358           302       191626                0
1   49   23267           662       150271                0
2   35  102745           807       123533                1
3   63  109588           573       479628                0
4   28   58513           805       449164                0

In [3]:
###STEP:3 feature and target separation

x=df[['age','income','credit_score','loan_amount']]
y=df[['approval_status']]
x

     age  income  credit_score  loan_amount
0     59   40358           302       191626
1     49   23267           662       150271
2     35  102745           807       123533
3     63  109588           573       479628
4     28   58513           805       449164
..   ...     ...           ...          ...
495   46   24621           629       395411
496   30   35034           406       254474
497   46  131927           525       184436
498   54  147858           517       497049
499   61   25126           805       393647

[500 rows x 4 columns]

In [4]:
### STEP:4 TRAIN_SPLIT SPLIT

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2, random_state=42)
x_train

     age  income  credit_score  loan_amount
249   62   55547           521       251693
433   49  135359           470       115198
19    64   67295           324       424901
322   49   37100           328       157876
332   41   27239           452       313311
..   ...     ...           ...          ...
106   27   92592           464        58947
270   31   57892           717       406927
348   47   44285           595        27431
435   48   48732           663        75326
102   62   68136           648       378929

[400 rows x 4 columns]

In [5]:
### STEP:5 TRAIN LOGISTIC REGRESSION MODEL
from sklearn.linear_model import LogisticRegression
log_model=LogisticRegression(max_iter=1000)
log_model.fit(x_train,y_train)

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression(max_iter=1000)

In [6]:
####STEP:6 PREDICTION & EVALUTION
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
y_pred_log=log_model.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test,y_pred_log))
print("\n Classification Report:\n",classification_report(y_test,y_pred_log))
print("Accuracy:",accuracy_score(y_test,y_pred_log))

Confusion Matrix:
 [[72  6]
 [ 3 19]]

 Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.92      0.94        78
           1       0.76      0.86      0.81        22

    accuracy                           0.91       100
   macro avg       0.86      0.89      0.87       100
weighted avg       0.92      0.91      0.91       100

Accuracy: 0.91

In [7]:
###STEP:7 FEATURE SCALING (MANDATORY)
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)
x_test

     age  income  credit_score  loan_amount
361   55  112234           847       317213
73    28  141954           439        50648
374   35   43386           595       423219
155   22   29435           623       268579
104   61  102873           569        74274
..   ...     ...           ...          ...
347   22  145917           448       210735
86    21  109780           620       490324
75    43  109112           389       407732
438   25   43954           796       225971
15    23   64425           836        12657

[100 rows x 4 columns]

In [8]:
x_test_scaled

array([[ 0.92513929,  0.8272248 ,  1.7192903 ,  0.36580029],
       [-1.20524543,  1.61698629, -0.79527866, -1.55462537],
       [-0.65292347, -1.00230073,  0.16617418,  1.12950386],
       [-1.67866426, -1.37302626,  0.33874264,  0.01542428],
       [ 1.39855812,  0.57847119,  0.00593204, -1.38441556],
       [ 1.24075184, -0.14948056,  1.40496918,  0.9737892 ],
       [-1.67866426,  0.38905599, -1.28216824,  0.52110431],
       [-0.7318266 , -0.87185191, -1.01715239,  1.08472167],
       [-1.04743915, -0.00486811,  0.86877433,  1.02071829],
       [-1.04743915, -1.1744698 ,  1.70696398,  0.0695361 ],
       [-0.96853602,  1.19013774, -1.41775774, -1.32948965],
       [-0.49511719,  1.79558612,  0.24629525, -0.99169242],
       [-0.49511719,  0.23203376, -0.00639428, -0.73776095],
       [ 0.45172046, -1.59552535, -1.57799988,  0.52177432],
       [-0.7318266 ,  0.33080709,  1.1153007 ,  0.49913827],
       [ 1.08294557,  1.62931635, -1.02947871, -1.64344051],
       [ 0.21501105, -1.50095061,  0.37572159,  0.9291655 ],
       [ 1.47746126,  0.73400531,  0.6160848 , -0.50895822],
       [-1.52085798, -0.12508618, -0.41932595,  0.60527265],
       [ 0.37281733, -0.65153184,  1.65765871, -0.40509321],
       [-0.02169836,  0.17423661, -0.71515759,  0.21708104],
       [-0.49511719, -0.44795301,  0.25245841,  0.13316486],
       [ 0.45172046,  0.03156402, -0.53642597, -0.16698248],
       [ 1.55636439, -0.44819217, -1.31914719, -0.61497733],
       [ 1.31965498,  0.95926803,  0.31409   ,  0.8336215 ],
       [-0.57402033, -1.34504446,  0.01825836, -1.45612039],
       [ 0.21501105,  1.3505348 , -0.26524696, -0.59077074],
       [-0.96853602, -1.11653979, -1.50404197,  0.99649008],
       [-1.44195484,  0.2966337 ,  0.31409   , -0.749785  ],
       [-0.02169836, -1.23872429,  0.4496795 ,  1.2620998 ],
       [ 1.08294557,  0.47831604,  0.1476847 ,  0.03896807],
       [-1.59976112, -0.08203727,  0.11070575,  0.91150765],
       [-0.57402033,  0.68930885,  0.49282162,  1.49486491],
       [-1.59976112, -0.87926589, -0.36385751, -1.35318473],
       [-0.65292347,  0.5750698 ,  1.47276393, -1.02953684],
       [ 0.68842988,  1.68341979,  0.67155324, -0.39668574],
       [ 0.21501105,  1.751554  , -1.36845246,  0.24759864],
       [-0.7318266 , -1.402257  , -0.27141012,  0.30590339],
       [ 0.68842988,  1.20252095, -0.55491545, -0.83626593],
       [ 0.45172046,  0.57219987, -1.49787881, -1.07503947],
       [ 1.47746126,  1.5598269 , -0.99249975, -1.03458708],
       [-1.20524543, -1.37533814, -0.20361537, -0.45164768],
       [-0.81072974,  1.33432502,  0.20315314,  0.19252144],
       [ 0.68842988, -0.70377514,  0.17233734, -0.78650553],
       [-0.65292347,  0.00988012,  0.07988995, -1.28336745],
       [-0.17950464, -1.32798434,  1.73161662, -1.8662276 ],
       [ 1.24075184, -1.08276499, -1.63963147, -0.53897152],
       [ 0.05720477, -0.01095342, -0.23443117, -0.80738372],
       [-1.7575674 , -0.98029796,  0.75167431, -1.61781466],
       [-1.67866426,  0.5829621 , -0.22210485, -0.73149317],
       [-0.65292347,  1.72503374, -0.96168396, -1.25679783],
       [ 1.63526753,  1.33323551, -1.47938933,  1.22001923],
       [ 0.29391419, -0.08636874, -1.56567356, -1.3380268 ],
       [ 1.08294557, -1.30446688,  0.11686891, -1.17157046],
       [ 1.08294557, -1.04625314,  0.99820067,  0.41841361],
       [-0.49511719, -1.1778712 ,  1.22623757, -1.69935341],
       [ 0.45172046,  0.86655344, -0.25292065, -1.3342157 ],
       [ 0.05720477, -0.6741458 , -0.35153119,  1.1325441 ],
       [-1.67866426,  1.7814225 , -0.36385751, -1.7988742 ],
       [-0.57402033,  0.70163891, -0.80144182, -1.27773365],
       [ 0.45172046,  1.16946364,  0.59759533, -1.25921849],
       [ 0.92513929,  0.38711613,  0.27094789, -1.26730176],
       [-1.36305171, -0.10664424, -0.98633659,  1.24970833],
       [ 1.63526753,  0.57010057,  1.05366911, -1.56948793],
       [-0.41621405,  1.19183844,  1.49125341,  1.08718555],
       [-1.12634229,  1.37522149,  1.03517963, -1.56907728],
       [-1.44195484, -1.12477754,  0.89342697, -0.2602499 ],
       [ 0.21501105, -0.5194886 , -0.81376813, -1.20356494],
       [ 1.31965498, -1.4952639 ,  0.10454259,  1.15543229],
       [ 1.63526753,  1.11852243, -1.38694194,  0.74147796],
       [-0.49511719, -0.19221059, -0.50561017, -1.52937414],
       [-1.59976112, -0.77209536,  1.27554284, -0.1328555 ],
       [ 0.13610791,  1.34859494,  1.12762702, -0.49405964],
       [ 0.76733302, -1.14497333, -1.15274189, -0.00639767],
       [ 0.92513929,  1.59928841,  0.05523731,  0.91604639],
       [ 1.1618487 ,  1.14767345,  0.58526901, -0.21345769],
       [ 0.76733302, -0.12048898, -1.34379983,  1.21192875],
       [ 1.00404243, -1.47796462, -0.93086816, -0.91744446],
       [-1.04743915,  1.77969523,  0.90575329, -1.48559335],
       [ 0.37281733, -1.3453102 , -0.0187206 ,  1.29451934],
       [ 0.37281733,  0.68200116, -1.36845246,  0.44632323],
       [ 0.13610791,  0.14877929, -0.04953639, -1.80205852],
       [-1.59976112,  1.76701971,  0.80097958, -1.36406329],
       [ 1.39855812,  1.02920923, -0.7891155 ,  0.46535711],
       [ 0.5306236 , -0.19058962,  1.06599543, -1.83915368],
       [ 0.05720477,  0.72696336,  0.92424276, -1.26225152],
       [ 0.76733302,  0.17370514,  0.67155324,  0.49418168],
       [-0.88963288, -1.16817191, -0.11733114, -1.19849308],
       [ 0.37281733, -0.7680562 ,  1.552885  , -0.05196514],
       [ 0.92513929,  1.37415855,  1.42345866, -1.28640048],
       [ 0.13610791, -0.1143771 , -0.85074709,  0.96324204],
       [ 0.76733302, -1.50597298,  0.65922692,  0.82800212],
       [ 0.13610791, -0.19723297, -0.74597338,  0.3820605 ],
       [ 0.92513929, -1.04048671, -1.19588401, -1.42033641],
       [ 1.08294557, -0.7352912 , -1.05413134,  1.55343622],
       [-1.67866426,  1.72229668, -0.73981022, -0.40130373],
       [-1.7575674 ,  0.76201368,  0.32025316,  1.61295129],
       [-0.02169836,  0.74426264, -1.10343662,  1.01793021],
       [-1.44195484, -0.98720704,  1.40496918, -0.29153836],
       [-1.59976112, -0.44322294,  1.65149555, -1.82832556]])

In [9]:
#### STEP:8 TRAIN KNN WITH DIFFERENT K Values
k=3
from sklearn.neighbors import KNeighborsClassifier
knn3=KNeighborsClassifier(n_neighbors=3)
knn3.fit(x_train_scaled,y_train)

y_pred_knn3=knn3.predict(x_test_scaled)
print("K=3 Accuracy:", accuracy_score(y_test,y_pred_knn3))

K=3 Accuracy: 0.9

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

In [10]:
k=5
from sklearn.neighbors import KNeighborsClassifier
knn5=KNeighborsClassifier(n_neighbors=5)
knn5.fit(x_train_scaled,y_train)

y_pred_knn5=knn5.predict(x_test_scaled)
print("K=5 Accuracy:", accuracy_score(y_test,y_pred_knn5))

K=5 Accuracy: 0.9

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

In [11]:
k=7
from sklearn.neighbors import KNeighborsClassifier
knn7=KNeighborsClassifier(n_neighbors=7)
knn7.fit(x_train_scaled,y_train)

y_pred_knn7=knn7.predict(x_test_scaled)
print("K=7 Accuracy:", accuracy_score(y_test,y_pred_knn7))

K=7 Accuracy: 0.89

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

In [12]:
####### STEP 9: TRAIN DECISION TREE MODEL
from sklearn.tree import DecisionTreeClassifier
dt_model=DecisionTreeClassifier(random_state=42)
dt_model.fit(x_train,y_train)

DecisionTreeClassifier(random_state=42)

In [13]:
#### STEP 10:PREDICTION&EVALUATION
y_pred_dt=dt_model.predict(x_test)
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred_dt))
print("\n Classification Report:\n",classification_report(y_test,y_pred_dt))
print("Accuracy:", accuracy_score(y_test,y_pred_dt))

Confusion Matrix:
 [[75  3]
 [ 3 19]]

 Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.96      0.96        78
           1       0.86      0.86      0.86        22

    accuracy                           0.94       100
   macro avg       0.91      0.91      0.91       100
weighted avg       0.94      0.94      0.94       100

Accuracy: 0.94

In [14]:
results=pd.DataFrame({
    'Model':['Logistic Regression','KNN (Best K)','Decision Tree'],
    'Accuracy':[accuracy_score(y_test,y_pred_log),max(
    accuracy_score(y_test,y_pred_knn3),
    accuracy_score(y_test,y_pred_knn5),
    accuracy_score(y_test,y_pred_knn7)),
               accuracy_score(y_test,y_pred_dt)]
})
results

                 Model  Accuracy
0  Logistic Regression      0.91
1         KNN (Best K)      0.90
2        Decision Tree      0.94